from .base import BaseLabelingStrategy
from .one_point import OnePointStrategy
from .picking import PickingStrategy
from .picking_small import PickingStrategy_small
from .picking_mid import PickingStrategy_mid
from .picking_big import PickingStrategy_big
from .picking_s import PickingStrategy_s
from .spanning import SpanningStrategy
from .poly import PolyStrategy
